-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_PlatformLink" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "platform" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "storeId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "PlatformLink_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_PlatformLink" ("createdAt", "id", "platform", "storeId", "updatedAt", "url") SELECT "createdAt", "id", "platform", "storeId", "updatedAt", "url" FROM "PlatformLink";
DROP TABLE "PlatformLink";
ALTER TABLE "new_PlatformLink" RENAME TO "PlatformLink";
CREATE UNIQUE INDEX "PlatformLink_storeId_platform_key" ON "PlatformLink"("storeId", "platform");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
