import type { Platform } from '@/lib/validation';

export type PlatformInput = {
  url: string;
  autoGenerated: boolean;
};

export function resolvePlatformInput(
  platform: Platform,
  providedUrl: string,
  name: string,
  address: string
): PlatformInput | null {
  void name;
  void address;

  if (providedUrl) {
    return { url: providedUrl, autoGenerated: false };
  }

  return null;
}
