import type { Platform } from '@/lib/validation';

export type PlatformInput = {
  url: string;
  autoGenerated: boolean;
};

function normalizeQuery(name: string, address: string): string {
  return `${name} ${address}`.trim();
}

function buildSearchUrl(platform: Platform, name: string, address: string): string {
  const query = encodeURIComponent(normalizeQuery(name, address));

  if (platform === 'GOOGLE') {
    return `https://www.google.com/maps/search/?api=1&query=${query}`;
  }
  if (platform === 'YANDEX') {
    return `https://yandex.ru/maps/?text=${query}`;
  }
  return `https://2gis.ru/search/${query}`;
}

function autoGenerateEnabled(): boolean {
  const value = process.env.AUTO_GENERATE_MISSING_LINKS;
  if (!value) {
    return true;
  }
  return !['false', '0', 'no'].includes(value.toLowerCase());
}

export function resolvePlatformInput(
  platform: Platform,
  providedUrl: string,
  name: string,
  address: string
): PlatformInput | null {
  if (providedUrl) {
    return { url: providedUrl, autoGenerated: false };
  }

  if (!autoGenerateEnabled()) {
    return null;
  }

  return {
    url: buildSearchUrl(platform, name, address),
    autoGenerated: true,
  };
}

