import type { Platform } from '@/lib/validation';

export type PlatformInput = {
  url: string;
  autoGenerated: boolean;
};

export function resolvePlatformInput(
  platform: Platform,
  providedUrl: string,
  _name: string,
  _address: string
): PlatformInput | null {
  if (providedUrl) {
    return { url: providedUrl, autoGenerated: false };
  }

  return null;
}
