
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PlatformLink` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PlatformLink
 * 
 */
export type PlatformLinkModel = runtime.Types.Result.DefaultSelection<Prisma.$PlatformLinkPayload>

export type AggregatePlatformLink = {
  _count: PlatformLinkCountAggregateOutputType | null
  _min: PlatformLinkMinAggregateOutputType | null
  _max: PlatformLinkMaxAggregateOutputType | null
}

export type PlatformLinkMinAggregateOutputType = {
  id: string | null
  platform: $Enums.Platform | null
  url: string | null
  storeId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PlatformLinkMaxAggregateOutputType = {
  id: string | null
  platform: $Enums.Platform | null
  url: string | null
  storeId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PlatformLinkCountAggregateOutputType = {
  id: number
  platform: number
  url: number
  storeId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PlatformLinkMinAggregateInputType = {
  id?: true
  platform?: true
  url?: true
  storeId?: true
  createdAt?: true
  updatedAt?: true
}

export type PlatformLinkMaxAggregateInputType = {
  id?: true
  platform?: true
  url?: true
  storeId?: true
  createdAt?: true
  updatedAt?: true
}

export type PlatformLinkCountAggregateInputType = {
  id?: true
  platform?: true
  url?: true
  storeId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PlatformLinkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PlatformLink to aggregate.
   */
  where?: Prisma.PlatformLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlatformLinks to fetch.
   */
  orderBy?: Prisma.PlatformLinkOrderByWithRelationInput | Prisma.PlatformLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PlatformLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlatformLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlatformLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PlatformLinks
  **/
  _count?: true | PlatformLinkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PlatformLinkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PlatformLinkMaxAggregateInputType
}

export type GetPlatformLinkAggregateType<T extends PlatformLinkAggregateArgs> = {
      [P in keyof T & keyof AggregatePlatformLink]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePlatformLink[P]>
    : Prisma.GetScalarType<T[P], AggregatePlatformLink[P]>
}




export type PlatformLinkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlatformLinkWhereInput
  orderBy?: Prisma.PlatformLinkOrderByWithAggregationInput | Prisma.PlatformLinkOrderByWithAggregationInput[]
  by: Prisma.PlatformLinkScalarFieldEnum[] | Prisma.PlatformLinkScalarFieldEnum
  having?: Prisma.PlatformLinkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PlatformLinkCountAggregateInputType | true
  _min?: PlatformLinkMinAggregateInputType
  _max?: PlatformLinkMaxAggregateInputType
}

export type PlatformLinkGroupByOutputType = {
  id: string
  platform: $Enums.Platform
  url: string
  storeId: string
  createdAt: Date
  updatedAt: Date
  _count: PlatformLinkCountAggregateOutputType | null
  _min: PlatformLinkMinAggregateOutputType | null
  _max: PlatformLinkMaxAggregateOutputType | null
}

type GetPlatformLinkGroupByPayload<T extends PlatformLinkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PlatformLinkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PlatformLinkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PlatformLinkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PlatformLinkGroupByOutputType[P]>
      }
    >
  >



export type PlatformLinkWhereInput = {
  AND?: Prisma.PlatformLinkWhereInput | Prisma.PlatformLinkWhereInput[]
  OR?: Prisma.PlatformLinkWhereInput[]
  NOT?: Prisma.PlatformLinkWhereInput | Prisma.PlatformLinkWhereInput[]
  id?: Prisma.StringFilter<"PlatformLink"> | string
  platform?: Prisma.EnumPlatformFilter<"PlatformLink"> | $Enums.Platform
  url?: Prisma.StringFilter<"PlatformLink"> | string
  storeId?: Prisma.StringFilter<"PlatformLink"> | string
  createdAt?: Prisma.DateTimeFilter<"PlatformLink"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PlatformLink"> | Date | string
  store?: Prisma.XOR<Prisma.StoreScalarRelationFilter, Prisma.StoreWhereInput>
}

export type PlatformLinkOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  url?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  store?: Prisma.StoreOrderByWithRelationInput
}

export type PlatformLinkWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  storeId_platform?: Prisma.PlatformLinkStoreIdPlatformCompoundUniqueInput
  AND?: Prisma.PlatformLinkWhereInput | Prisma.PlatformLinkWhereInput[]
  OR?: Prisma.PlatformLinkWhereInput[]
  NOT?: Prisma.PlatformLinkWhereInput | Prisma.PlatformLinkWhereInput[]
  platform?: Prisma.EnumPlatformFilter<"PlatformLink"> | $Enums.Platform
  url?: Prisma.StringFilter<"PlatformLink"> | string
  storeId?: Prisma.StringFilter<"PlatformLink"> | string
  createdAt?: Prisma.DateTimeFilter<"PlatformLink"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PlatformLink"> | Date | string
  store?: Prisma.XOR<Prisma.StoreScalarRelationFilter, Prisma.StoreWhereInput>
}, "id" | "storeId_platform">

export type PlatformLinkOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  url?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PlatformLinkCountOrderByAggregateInput
  _max?: Prisma.PlatformLinkMaxOrderByAggregateInput
  _min?: Prisma.PlatformLinkMinOrderByAggregateInput
}

export type PlatformLinkScalarWhereWithAggregatesInput = {
  AND?: Prisma.PlatformLinkScalarWhereWithAggregatesInput | Prisma.PlatformLinkScalarWhereWithAggregatesInput[]
  OR?: Prisma.PlatformLinkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PlatformLinkScalarWhereWithAggregatesInput | Prisma.PlatformLinkScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PlatformLink"> | string
  platform?: Prisma.EnumPlatformWithAggregatesFilter<"PlatformLink"> | $Enums.Platform
  url?: Prisma.StringWithAggregatesFilter<"PlatformLink"> | string
  storeId?: Prisma.StringWithAggregatesFilter<"PlatformLink"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PlatformLink"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PlatformLink"> | Date | string
}

export type PlatformLinkCreateInput = {
  id?: string
  platform: $Enums.Platform
  url: string
  createdAt?: Date | string
  updatedAt?: Date | string
  store: Prisma.StoreCreateNestedOneWithoutPlatformLinksInput
}

export type PlatformLinkUncheckedCreateInput = {
  id?: string
  platform: $Enums.Platform
  url: string
  storeId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlatformLinkUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.EnumPlatformFieldUpdateOperationsInput | $Enums.Platform
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  store?: Prisma.StoreUpdateOneRequiredWithoutPlatformLinksNestedInput
}

export type PlatformLinkUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.EnumPlatformFieldUpdateOperationsInput | $Enums.Platform
  url?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlatformLinkCreateManyInput = {
  id?: string
  platform: $Enums.Platform
  url: string
  storeId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlatformLinkUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.EnumPlatformFieldUpdateOperationsInput | $Enums.Platform
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlatformLinkUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.EnumPlatformFieldUpdateOperationsInput | $Enums.Platform
  url?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlatformLinkListRelationFilter = {
  every?: Prisma.PlatformLinkWhereInput
  some?: Prisma.PlatformLinkWhereInput
  none?: Prisma.PlatformLinkWhereInput
}

export type PlatformLinkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PlatformLinkStoreIdPlatformCompoundUniqueInput = {
  storeId: string
  platform: $Enums.Platform
}

export type PlatformLinkCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  url?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlatformLinkMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  url?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlatformLinkMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  platform?: Prisma.SortOrder
  url?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlatformLinkCreateNestedManyWithoutStoreInput = {
  create?: Prisma.XOR<Prisma.PlatformLinkCreateWithoutStoreInput, Prisma.PlatformLinkUncheckedCreateWithoutStoreInput> | Prisma.PlatformLinkCreateWithoutStoreInput[] | Prisma.PlatformLinkUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.PlatformLinkCreateOrConnectWithoutStoreInput | Prisma.PlatformLinkCreateOrConnectWithoutStoreInput[]
  createMany?: Prisma.PlatformLinkCreateManyStoreInputEnvelope
  connect?: Prisma.PlatformLinkWhereUniqueInput | Prisma.PlatformLinkWhereUniqueInput[]
}

export type PlatformLinkUncheckedCreateNestedManyWithoutStoreInput = {
  create?: Prisma.XOR<Prisma.PlatformLinkCreateWithoutStoreInput, Prisma.PlatformLinkUncheckedCreateWithoutStoreInput> | Prisma.PlatformLinkCreateWithoutStoreInput[] | Prisma.PlatformLinkUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.PlatformLinkCreateOrConnectWithoutStoreInput | Prisma.PlatformLinkCreateOrConnectWithoutStoreInput[]
  createMany?: Prisma.PlatformLinkCreateManyStoreInputEnvelope
  connect?: Prisma.PlatformLinkWhereUniqueInput | Prisma.PlatformLinkWhereUniqueInput[]
}

export type PlatformLinkUpdateManyWithoutStoreNestedInput = {
  create?: Prisma.XOR<Prisma.PlatformLinkCreateWithoutStoreInput, Prisma.PlatformLinkUncheckedCreateWithoutStoreInput> | Prisma.PlatformLinkCreateWithoutStoreInput[] | Prisma.PlatformLinkUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.PlatformLinkCreateOrConnectWithoutStoreInput | Prisma.PlatformLinkCreateOrConnectWithoutStoreInput[]
  upsert?: Prisma.PlatformLinkUpsertWithWhereUniqueWithoutStoreInput | Prisma.PlatformLinkUpsertWithWhereUniqueWithoutStoreInput[]
  createMany?: Prisma.PlatformLinkCreateManyStoreInputEnvelope
  set?: Prisma.PlatformLinkWhereUniqueInput | Prisma.PlatformLinkWhereUniqueInput[]
  disconnect?: Prisma.PlatformLinkWhereUniqueInput | Prisma.PlatformLinkWhereUniqueInput[]
  delete?: Prisma.PlatformLinkWhereUniqueInput | Prisma.PlatformLinkWhereUniqueInput[]
  connect?: Prisma.PlatformLinkWhereUniqueInput | Prisma.PlatformLinkWhereUniqueInput[]
  update?: Prisma.PlatformLinkUpdateWithWhereUniqueWithoutStoreInput | Prisma.PlatformLinkUpdateWithWhereUniqueWithoutStoreInput[]
  updateMany?: Prisma.PlatformLinkUpdateManyWithWhereWithoutStoreInput | Prisma.PlatformLinkUpdateManyWithWhereWithoutStoreInput[]
  deleteMany?: Prisma.PlatformLinkScalarWhereInput | Prisma.PlatformLinkScalarWhereInput[]
}

export type PlatformLinkUncheckedUpdateManyWithoutStoreNestedInput = {
  create?: Prisma.XOR<Prisma.PlatformLinkCreateWithoutStoreInput, Prisma.PlatformLinkUncheckedCreateWithoutStoreInput> | Prisma.PlatformLinkCreateWithoutStoreInput[] | Prisma.PlatformLinkUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.PlatformLinkCreateOrConnectWithoutStoreInput | Prisma.PlatformLinkCreateOrConnectWithoutStoreInput[]
  upsert?: Prisma.PlatformLinkUpsertWithWhereUniqueWithoutStoreInput | Prisma.PlatformLinkUpsertWithWhereUniqueWithoutStoreInput[]
  createMany?: Prisma.PlatformLinkCreateManyStoreInputEnvelope
  set?: Prisma.PlatformLinkWhereUniqueInput | Prisma.PlatformLinkWhereUniqueInput[]
  disconnect?: Prisma.PlatformLinkWhereUniqueInput | Prisma.PlatformLinkWhereUniqueInput[]
  delete?: Prisma.PlatformLinkWhereUniqueInput | Prisma.PlatformLinkWhereUniqueInput[]
  connect?: Prisma.PlatformLinkWhereUniqueInput | Prisma.PlatformLinkWhereUniqueInput[]
  update?: Prisma.PlatformLinkUpdateWithWhereUniqueWithoutStoreInput | Prisma.PlatformLinkUpdateWithWhereUniqueWithoutStoreInput[]
  updateMany?: Prisma.PlatformLinkUpdateManyWithWhereWithoutStoreInput | Prisma.PlatformLinkUpdateManyWithWhereWithoutStoreInput[]
  deleteMany?: Prisma.PlatformLinkScalarWhereInput | Prisma.PlatformLinkScalarWhereInput[]
}

export type EnumPlatformFieldUpdateOperationsInput = {
  set?: $Enums.Platform
}

export type PlatformLinkCreateWithoutStoreInput = {
  id?: string
  platform: $Enums.Platform
  url: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlatformLinkUncheckedCreateWithoutStoreInput = {
  id?: string
  platform: $Enums.Platform
  url: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlatformLinkCreateOrConnectWithoutStoreInput = {
  where: Prisma.PlatformLinkWhereUniqueInput
  create: Prisma.XOR<Prisma.PlatformLinkCreateWithoutStoreInput, Prisma.PlatformLinkUncheckedCreateWithoutStoreInput>
}

export type PlatformLinkCreateManyStoreInputEnvelope = {
  data: Prisma.PlatformLinkCreateManyStoreInput | Prisma.PlatformLinkCreateManyStoreInput[]
}

export type PlatformLinkUpsertWithWhereUniqueWithoutStoreInput = {
  where: Prisma.PlatformLinkWhereUniqueInput
  update: Prisma.XOR<Prisma.PlatformLinkUpdateWithoutStoreInput, Prisma.PlatformLinkUncheckedUpdateWithoutStoreInput>
  create: Prisma.XOR<Prisma.PlatformLinkCreateWithoutStoreInput, Prisma.PlatformLinkUncheckedCreateWithoutStoreInput>
}

export type PlatformLinkUpdateWithWhereUniqueWithoutStoreInput = {
  where: Prisma.PlatformLinkWhereUniqueInput
  data: Prisma.XOR<Prisma.PlatformLinkUpdateWithoutStoreInput, Prisma.PlatformLinkUncheckedUpdateWithoutStoreInput>
}

export type PlatformLinkUpdateManyWithWhereWithoutStoreInput = {
  where: Prisma.PlatformLinkScalarWhereInput
  data: Prisma.XOR<Prisma.PlatformLinkUpdateManyMutationInput, Prisma.PlatformLinkUncheckedUpdateManyWithoutStoreInput>
}

export type PlatformLinkScalarWhereInput = {
  AND?: Prisma.PlatformLinkScalarWhereInput | Prisma.PlatformLinkScalarWhereInput[]
  OR?: Prisma.PlatformLinkScalarWhereInput[]
  NOT?: Prisma.PlatformLinkScalarWhereInput | Prisma.PlatformLinkScalarWhereInput[]
  id?: Prisma.StringFilter<"PlatformLink"> | string
  platform?: Prisma.EnumPlatformFilter<"PlatformLink"> | $Enums.Platform
  url?: Prisma.StringFilter<"PlatformLink"> | string
  storeId?: Prisma.StringFilter<"PlatformLink"> | string
  createdAt?: Prisma.DateTimeFilter<"PlatformLink"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PlatformLink"> | Date | string
}

export type PlatformLinkCreateManyStoreInput = {
  id?: string
  platform: $Enums.Platform
  url: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlatformLinkUpdateWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.EnumPlatformFieldUpdateOperationsInput | $Enums.Platform
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlatformLinkUncheckedUpdateWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.EnumPlatformFieldUpdateOperationsInput | $Enums.Platform
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlatformLinkUncheckedUpdateManyWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platform?: Prisma.EnumPlatformFieldUpdateOperationsInput | $Enums.Platform
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PlatformLinkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  platform?: boolean
  url?: boolean
  storeId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}, ExtArgs["result"]["platformLink"]>

export type PlatformLinkSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  platform?: boolean
  url?: boolean
  storeId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}, ExtArgs["result"]["platformLink"]>

export type PlatformLinkSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  platform?: boolean
  url?: boolean
  storeId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}, ExtArgs["result"]["platformLink"]>

export type PlatformLinkSelectScalar = {
  id?: boolean
  platform?: boolean
  url?: boolean
  storeId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PlatformLinkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "platform" | "url" | "storeId" | "createdAt" | "updatedAt", ExtArgs["result"]["platformLink"]>
export type PlatformLinkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}
export type PlatformLinkIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}
export type PlatformLinkIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}

export type $PlatformLinkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PlatformLink"
  objects: {
    store: Prisma.$StorePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    platform: $Enums.Platform
    url: string
    storeId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["platformLink"]>
  composites: {}
}

export type PlatformLinkGetPayload<S extends boolean | null | undefined | PlatformLinkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PlatformLinkPayload, S>

export type PlatformLinkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PlatformLinkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PlatformLinkCountAggregateInputType | true
  }

export interface PlatformLinkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PlatformLink'], meta: { name: 'PlatformLink' } }
  /**
   * Find zero or one PlatformLink that matches the filter.
   * @param {PlatformLinkFindUniqueArgs} args - Arguments to find a PlatformLink
   * @example
   * // Get one PlatformLink
   * const platformLink = await prisma.platformLink.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PlatformLinkFindUniqueArgs>(args: Prisma.SelectSubset<T, PlatformLinkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PlatformLinkClient<runtime.Types.Result.GetResult<Prisma.$PlatformLinkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PlatformLink that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PlatformLinkFindUniqueOrThrowArgs} args - Arguments to find a PlatformLink
   * @example
   * // Get one PlatformLink
   * const platformLink = await prisma.platformLink.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PlatformLinkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PlatformLinkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlatformLinkClient<runtime.Types.Result.GetResult<Prisma.$PlatformLinkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PlatformLink that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformLinkFindFirstArgs} args - Arguments to find a PlatformLink
   * @example
   * // Get one PlatformLink
   * const platformLink = await prisma.platformLink.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PlatformLinkFindFirstArgs>(args?: Prisma.SelectSubset<T, PlatformLinkFindFirstArgs<ExtArgs>>): Prisma.Prisma__PlatformLinkClient<runtime.Types.Result.GetResult<Prisma.$PlatformLinkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PlatformLink that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformLinkFindFirstOrThrowArgs} args - Arguments to find a PlatformLink
   * @example
   * // Get one PlatformLink
   * const platformLink = await prisma.platformLink.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PlatformLinkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PlatformLinkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlatformLinkClient<runtime.Types.Result.GetResult<Prisma.$PlatformLinkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PlatformLinks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformLinkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PlatformLinks
   * const platformLinks = await prisma.platformLink.findMany()
   * 
   * // Get first 10 PlatformLinks
   * const platformLinks = await prisma.platformLink.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const platformLinkWithIdOnly = await prisma.platformLink.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PlatformLinkFindManyArgs>(args?: Prisma.SelectSubset<T, PlatformLinkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlatformLinkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PlatformLink.
   * @param {PlatformLinkCreateArgs} args - Arguments to create a PlatformLink.
   * @example
   * // Create one PlatformLink
   * const PlatformLink = await prisma.platformLink.create({
   *   data: {
   *     // ... data to create a PlatformLink
   *   }
   * })
   * 
   */
  create<T extends PlatformLinkCreateArgs>(args: Prisma.SelectSubset<T, PlatformLinkCreateArgs<ExtArgs>>): Prisma.Prisma__PlatformLinkClient<runtime.Types.Result.GetResult<Prisma.$PlatformLinkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PlatformLinks.
   * @param {PlatformLinkCreateManyArgs} args - Arguments to create many PlatformLinks.
   * @example
   * // Create many PlatformLinks
   * const platformLink = await prisma.platformLink.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PlatformLinkCreateManyArgs>(args?: Prisma.SelectSubset<T, PlatformLinkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PlatformLinks and returns the data saved in the database.
   * @param {PlatformLinkCreateManyAndReturnArgs} args - Arguments to create many PlatformLinks.
   * @example
   * // Create many PlatformLinks
   * const platformLink = await prisma.platformLink.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PlatformLinks and only return the `id`
   * const platformLinkWithIdOnly = await prisma.platformLink.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PlatformLinkCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PlatformLinkCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlatformLinkPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PlatformLink.
   * @param {PlatformLinkDeleteArgs} args - Arguments to delete one PlatformLink.
   * @example
   * // Delete one PlatformLink
   * const PlatformLink = await prisma.platformLink.delete({
   *   where: {
   *     // ... filter to delete one PlatformLink
   *   }
   * })
   * 
   */
  delete<T extends PlatformLinkDeleteArgs>(args: Prisma.SelectSubset<T, PlatformLinkDeleteArgs<ExtArgs>>): Prisma.Prisma__PlatformLinkClient<runtime.Types.Result.GetResult<Prisma.$PlatformLinkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PlatformLink.
   * @param {PlatformLinkUpdateArgs} args - Arguments to update one PlatformLink.
   * @example
   * // Update one PlatformLink
   * const platformLink = await prisma.platformLink.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PlatformLinkUpdateArgs>(args: Prisma.SelectSubset<T, PlatformLinkUpdateArgs<ExtArgs>>): Prisma.Prisma__PlatformLinkClient<runtime.Types.Result.GetResult<Prisma.$PlatformLinkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PlatformLinks.
   * @param {PlatformLinkDeleteManyArgs} args - Arguments to filter PlatformLinks to delete.
   * @example
   * // Delete a few PlatformLinks
   * const { count } = await prisma.platformLink.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PlatformLinkDeleteManyArgs>(args?: Prisma.SelectSubset<T, PlatformLinkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PlatformLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformLinkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PlatformLinks
   * const platformLink = await prisma.platformLink.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PlatformLinkUpdateManyArgs>(args: Prisma.SelectSubset<T, PlatformLinkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PlatformLinks and returns the data updated in the database.
   * @param {PlatformLinkUpdateManyAndReturnArgs} args - Arguments to update many PlatformLinks.
   * @example
   * // Update many PlatformLinks
   * const platformLink = await prisma.platformLink.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PlatformLinks and only return the `id`
   * const platformLinkWithIdOnly = await prisma.platformLink.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PlatformLinkUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PlatformLinkUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlatformLinkPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PlatformLink.
   * @param {PlatformLinkUpsertArgs} args - Arguments to update or create a PlatformLink.
   * @example
   * // Update or create a PlatformLink
   * const platformLink = await prisma.platformLink.upsert({
   *   create: {
   *     // ... data to create a PlatformLink
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PlatformLink we want to update
   *   }
   * })
   */
  upsert<T extends PlatformLinkUpsertArgs>(args: Prisma.SelectSubset<T, PlatformLinkUpsertArgs<ExtArgs>>): Prisma.Prisma__PlatformLinkClient<runtime.Types.Result.GetResult<Prisma.$PlatformLinkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PlatformLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformLinkCountArgs} args - Arguments to filter PlatformLinks to count.
   * @example
   * // Count the number of PlatformLinks
   * const count = await prisma.platformLink.count({
   *   where: {
   *     // ... the filter for the PlatformLinks we want to count
   *   }
   * })
  **/
  count<T extends PlatformLinkCountArgs>(
    args?: Prisma.Subset<T, PlatformLinkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PlatformLinkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PlatformLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformLinkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PlatformLinkAggregateArgs>(args: Prisma.Subset<T, PlatformLinkAggregateArgs>): Prisma.PrismaPromise<GetPlatformLinkAggregateType<T>>

  /**
   * Group by PlatformLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformLinkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PlatformLinkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PlatformLinkGroupByArgs['orderBy'] }
      : { orderBy?: PlatformLinkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PlatformLinkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPlatformLinkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PlatformLink model
 */
readonly fields: PlatformLinkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PlatformLink.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PlatformLinkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  store<T extends Prisma.StoreDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StoreDefaultArgs<ExtArgs>>): Prisma.Prisma__StoreClient<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PlatformLink model
 */
export interface PlatformLinkFieldRefs {
  readonly id: Prisma.FieldRef<"PlatformLink", 'String'>
  readonly platform: Prisma.FieldRef<"PlatformLink", 'Platform'>
  readonly url: Prisma.FieldRef<"PlatformLink", 'String'>
  readonly storeId: Prisma.FieldRef<"PlatformLink", 'String'>
  readonly createdAt: Prisma.FieldRef<"PlatformLink", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PlatformLink", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PlatformLink findUnique
 */
export type PlatformLinkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformLink
   */
  select?: Prisma.PlatformLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformLink
   */
  omit?: Prisma.PlatformLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlatformLinkInclude<ExtArgs> | null
  /**
   * Filter, which PlatformLink to fetch.
   */
  where: Prisma.PlatformLinkWhereUniqueInput
}

/**
 * PlatformLink findUniqueOrThrow
 */
export type PlatformLinkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformLink
   */
  select?: Prisma.PlatformLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformLink
   */
  omit?: Prisma.PlatformLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlatformLinkInclude<ExtArgs> | null
  /**
   * Filter, which PlatformLink to fetch.
   */
  where: Prisma.PlatformLinkWhereUniqueInput
}

/**
 * PlatformLink findFirst
 */
export type PlatformLinkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformLink
   */
  select?: Prisma.PlatformLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformLink
   */
  omit?: Prisma.PlatformLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlatformLinkInclude<ExtArgs> | null
  /**
   * Filter, which PlatformLink to fetch.
   */
  where?: Prisma.PlatformLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlatformLinks to fetch.
   */
  orderBy?: Prisma.PlatformLinkOrderByWithRelationInput | Prisma.PlatformLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PlatformLinks.
   */
  cursor?: Prisma.PlatformLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlatformLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlatformLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlatformLinks.
   */
  distinct?: Prisma.PlatformLinkScalarFieldEnum | Prisma.PlatformLinkScalarFieldEnum[]
}

/**
 * PlatformLink findFirstOrThrow
 */
export type PlatformLinkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformLink
   */
  select?: Prisma.PlatformLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformLink
   */
  omit?: Prisma.PlatformLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlatformLinkInclude<ExtArgs> | null
  /**
   * Filter, which PlatformLink to fetch.
   */
  where?: Prisma.PlatformLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlatformLinks to fetch.
   */
  orderBy?: Prisma.PlatformLinkOrderByWithRelationInput | Prisma.PlatformLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PlatformLinks.
   */
  cursor?: Prisma.PlatformLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlatformLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlatformLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlatformLinks.
   */
  distinct?: Prisma.PlatformLinkScalarFieldEnum | Prisma.PlatformLinkScalarFieldEnum[]
}

/**
 * PlatformLink findMany
 */
export type PlatformLinkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformLink
   */
  select?: Prisma.PlatformLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformLink
   */
  omit?: Prisma.PlatformLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlatformLinkInclude<ExtArgs> | null
  /**
   * Filter, which PlatformLinks to fetch.
   */
  where?: Prisma.PlatformLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlatformLinks to fetch.
   */
  orderBy?: Prisma.PlatformLinkOrderByWithRelationInput | Prisma.PlatformLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PlatformLinks.
   */
  cursor?: Prisma.PlatformLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlatformLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlatformLinks.
   */
  skip?: number
  distinct?: Prisma.PlatformLinkScalarFieldEnum | Prisma.PlatformLinkScalarFieldEnum[]
}

/**
 * PlatformLink create
 */
export type PlatformLinkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformLink
   */
  select?: Prisma.PlatformLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformLink
   */
  omit?: Prisma.PlatformLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlatformLinkInclude<ExtArgs> | null
  /**
   * The data needed to create a PlatformLink.
   */
  data: Prisma.XOR<Prisma.PlatformLinkCreateInput, Prisma.PlatformLinkUncheckedCreateInput>
}

/**
 * PlatformLink createMany
 */
export type PlatformLinkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PlatformLinks.
   */
  data: Prisma.PlatformLinkCreateManyInput | Prisma.PlatformLinkCreateManyInput[]
}

/**
 * PlatformLink createManyAndReturn
 */
export type PlatformLinkCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformLink
   */
  select?: Prisma.PlatformLinkSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformLink
   */
  omit?: Prisma.PlatformLinkOmit<ExtArgs> | null
  /**
   * The data used to create many PlatformLinks.
   */
  data: Prisma.PlatformLinkCreateManyInput | Prisma.PlatformLinkCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlatformLinkIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PlatformLink update
 */
export type PlatformLinkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformLink
   */
  select?: Prisma.PlatformLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformLink
   */
  omit?: Prisma.PlatformLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlatformLinkInclude<ExtArgs> | null
  /**
   * The data needed to update a PlatformLink.
   */
  data: Prisma.XOR<Prisma.PlatformLinkUpdateInput, Prisma.PlatformLinkUncheckedUpdateInput>
  /**
   * Choose, which PlatformLink to update.
   */
  where: Prisma.PlatformLinkWhereUniqueInput
}

/**
 * PlatformLink updateMany
 */
export type PlatformLinkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PlatformLinks.
   */
  data: Prisma.XOR<Prisma.PlatformLinkUpdateManyMutationInput, Prisma.PlatformLinkUncheckedUpdateManyInput>
  /**
   * Filter which PlatformLinks to update
   */
  where?: Prisma.PlatformLinkWhereInput
  /**
   * Limit how many PlatformLinks to update.
   */
  limit?: number
}

/**
 * PlatformLink updateManyAndReturn
 */
export type PlatformLinkUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformLink
   */
  select?: Prisma.PlatformLinkSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformLink
   */
  omit?: Prisma.PlatformLinkOmit<ExtArgs> | null
  /**
   * The data used to update PlatformLinks.
   */
  data: Prisma.XOR<Prisma.PlatformLinkUpdateManyMutationInput, Prisma.PlatformLinkUncheckedUpdateManyInput>
  /**
   * Filter which PlatformLinks to update
   */
  where?: Prisma.PlatformLinkWhereInput
  /**
   * Limit how many PlatformLinks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlatformLinkIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PlatformLink upsert
 */
export type PlatformLinkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformLink
   */
  select?: Prisma.PlatformLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformLink
   */
  omit?: Prisma.PlatformLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlatformLinkInclude<ExtArgs> | null
  /**
   * The filter to search for the PlatformLink to update in case it exists.
   */
  where: Prisma.PlatformLinkWhereUniqueInput
  /**
   * In case the PlatformLink found by the `where` argument doesn't exist, create a new PlatformLink with this data.
   */
  create: Prisma.XOR<Prisma.PlatformLinkCreateInput, Prisma.PlatformLinkUncheckedCreateInput>
  /**
   * In case the PlatformLink was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PlatformLinkUpdateInput, Prisma.PlatformLinkUncheckedUpdateInput>
}

/**
 * PlatformLink delete
 */
export type PlatformLinkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformLink
   */
  select?: Prisma.PlatformLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformLink
   */
  omit?: Prisma.PlatformLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlatformLinkInclude<ExtArgs> | null
  /**
   * Filter which PlatformLink to delete.
   */
  where: Prisma.PlatformLinkWhereUniqueInput
}

/**
 * PlatformLink deleteMany
 */
export type PlatformLinkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PlatformLinks to delete
   */
  where?: Prisma.PlatformLinkWhereInput
  /**
   * Limit how many PlatformLinks to delete.
   */
  limit?: number
}

/**
 * PlatformLink without action
 */
export type PlatformLinkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformLink
   */
  select?: Prisma.PlatformLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformLink
   */
  omit?: Prisma.PlatformLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlatformLinkInclude<ExtArgs> | null
}
