import { PrismaClient } from '@prisma/client';
import { randomBytes, createHash } from 'node:crypto';

const prisma = new PrismaClient();

async function main() {
  const user = await prisma.user.findUnique({ where: { email: 'admin@demo.com' } });
  if (!user) throw new Error('admin user not found');

  const stores = [
    {
      name: 'Сырная лавка',
      address: 'Ташкент',
      yandexUrl:
        'https://yandex.uz/maps/10335/tashkent/search/%D1%81%D1%8B%D1%80%D0%BD%D0%B0%D1%8F%20%D0%BB%D0%B0%D0%B2%D0%BA%D0%B0/?ll=69.280280%2C41.311151&sll=69.279737%2C41.311151&sspn=0.221100%2C0.098627&z=11',
    },
  ];

  for (const s of stores) {
    let store = await prisma.store.findFirst({
      where: { tenantId: user.tenantId, name: s.name },
      include: { qrCodes: true },
    });

    if (!store) {
      store = await prisma.store.create({
        data: {
          name: s.name,
          address: s.address,
          tenantId: user.tenantId,
          qrCodes: {
            create: {
              name: 'Default',
              slug: randomBytes(3).toString('hex'),
            },
          },
        },
        include: { qrCodes: true },
      });
    }

    const query = encodeURIComponent(`${s.name} ${s.address ?? ''}`.trim());
    const links = [
      { platform: 'YANDEX', url: s.yandexUrl, autoGenerated: false },
      {
        platform: 'GOOGLE',
        url: `https://www.google.com/maps/search/?api=1&query=${query}`,
        autoGenerated: true,
      },
      {
        platform: 'TWOGIS',
        url: `https://2gis.ru/search/${query}`,
        autoGenerated: true,
      },
    ];

    for (const link of links) {
      await prisma.platformLink.upsert({
        where: {
          storeId_platform: {
            storeId: store.id,
            platform: link.platform,
          },
        },
        create: {
          storeId: store.id,
          platform: link.platform,
          url: link.url,
          autoGenerated: link.autoGenerated,
        },
        update: {
          url: link.url,
          autoGenerated: link.autoGenerated,
        },
      });
    }

    console.log(`STORE|${store.id}|${store.name}|${store.qrCodes[0]?.slug ?? ''}`);
  }

  const token = randomBytes(32).toString('hex');
  const tokenHash = createHash('sha256').update(token).digest('hex');
  await prisma.session.create({
    data: {
      tokenHash,
      userId: user.id,
      expiresAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    },
  });

  console.log(`SESSION|${token}`);
}

main()
  .finally(async () => {
    await prisma.$disconnect();
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
